// Mocks generated by Mockito 5.4.4 from annotations
// in flauncher/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i13;
import 'dart:ui' as _i4;

import 'package:drift/drift.dart' as _i6;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i8;
import 'package:flauncher/database.dart' as _i7;
import 'package:flauncher/flauncher_channel.dart' as _i12;
import 'package:flauncher/gradients.dart' as _i2;
import 'package:flauncher/models/app.dart' as _i16;
import 'package:flauncher/models/category.dart' as _i3;
import 'package:flauncher/providers/apps_service.dart' as _i15;
import 'package:flauncher/providers/settings_service.dart' as _i17;
import 'package:flauncher/providers/wallpaper_service.dart' as _i14;
import 'package:flutter/cupertino.dart' as _i10;
import 'package:flutter/services.dart' as _i11;
import 'package:image_picker/image_picker.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFLauncherGradient_0 extends _i1.SmartFake
    implements _i2.FLauncherGradient {
  _FakeFLauncherGradient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_1 extends _i1.SmartFake implements _i3.Category {
  _FakeCategory_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_2 extends _i1.SmartFake implements _i4.Color {
  _FakeColor_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLostDataResponse_3 extends _i1.SmartFake
    implements _i5.LostDataResponse {
  _FakeLostDataResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_4 extends _i1.SmartFake
    implements _i6.MigrationStrategy {
  _FakeMigrationStrategy_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppsTable_5 extends _i1.SmartFake implements _i7.$AppsTable {
  _Fake$AppsTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CategoriesTable_6 extends _i1.SmartFake
    implements _i7.$CategoriesTable {
  _Fake$CategoriesTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppsCategoriesTable_7 extends _i1.SmartFake
    implements _i7.$AppsCategoriesTable {
  _Fake$AppsCategoriesTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$LauncherSpacersTable_8 extends _i1.SmartFake
    implements _i7.$LauncherSpacersTable {
  _Fake$LauncherSpacersTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$FLauncherDatabaseManager_9 extends _i1.SmartFake
    implements _i7.$FLauncherDatabaseManager {
  _Fake$FLauncherDatabaseManager_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_10 extends _i1.SmartFake
    implements _i6.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_11 extends _i1.SmartFake
    implements _i6.GeneratedDatabase {
  _FakeGeneratedDatabase_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_12 extends _i1.SmartFake
    implements _i6.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_13 extends _i1.SmartFake
    implements _i6.DatabaseConnection {
  _FakeDatabaseConnection_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_14 extends _i1.SmartFake implements _i6.QueryExecutor {
  _FakeQueryExecutor_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_15 extends _i1.SmartFake
    implements _i8.StreamQueryStore {
  _FakeStreamQueryStore_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_16 extends _i1.SmartFake
    implements _i6.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_17 extends _i1.SmartFake implements _i6.Migrator {
  _FakeMigrator_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_18<T1> extends _i1.SmartFake implements _i9.Future<T1> {
  _FakeFuture_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_19<T1 extends _i6.Table, D1> extends _i1.SmartFake
    implements _i6.InsertStatement<T1, D1> {
  _FakeInsertStatement_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_20<T extends _i6.Table, D> extends _i1.SmartFake
    implements _i6.UpdateStatement<T, D> {
  _FakeUpdateStatement_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_21<T1 extends _i6.HasResultSet, D>
    extends _i1.SmartFake implements _i6.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_22<FirstT extends _i6.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i6.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_23<T> extends _i1.SmartFake implements _i6.Selectable<T> {
  _FakeSelectable_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_24<T1 extends _i6.Table, D1> extends _i1.SmartFake
    implements _i6.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_25 extends _i1.SmartFake
    implements _i6.GenerationContext {
  _FakeGenerationContext_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageStream_26 extends _i1.SmartFake implements _i10.ImageStream {
  _FakeImageStream_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i11.DiagnosticLevel? minLevel = _i11.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeImageStreamCompleter_27 extends _i1.SmartFake
    implements _i10.ImageStreamCompleter {
  _FakeImageStreamCompleter_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString(
          {_i11.DiagnosticLevel? minLevel = _i11.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [FLauncherChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockFLauncherChannel extends _i1.Mock implements _i12.FLauncherChannel {
  MockFLauncherChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<Map<dynamic, dynamic>>> getApplications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplications,
          [],
        ),
        returnValue: _i9.Future<List<Map<dynamic, dynamic>>>.value(
            <Map<dynamic, dynamic>>[]),
      ) as _i9.Future<List<Map<dynamic, dynamic>>>);

  @override
  _i9.Future<_i13.Uint8List> getApplicationBanner(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationBanner,
          [packageName],
        ),
        returnValue: _i9.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
      ) as _i9.Future<_i13.Uint8List>);

  @override
  _i9.Future<_i13.Uint8List> getApplicationIcon(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApplicationIcon,
          [packageName],
        ),
        returnValue: _i9.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
      ) as _i9.Future<_i13.Uint8List>);

  @override
  _i9.Future<void> launchActivityFromAction(String? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #launchActivityFromAction,
          [action],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> launchApp(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #launchApp,
          [packageName],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> openSettings() => (super.noSuchMethod(
        Invocation.method(
          #openSettings,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> openAppInfo(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #openAppInfo,
          [packageName],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> uninstallApp(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #uninstallApp,
          [packageName],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> isDefaultLauncher() => (super.noSuchMethod(
        Invocation.method(
          #isDefaultLauncher,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> checkForGetContentAvailability() => (super.noSuchMethod(
        Invocation.method(
          #checkForGetContentAvailability,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<Map<String, dynamic>> getActiveNetworkInformation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNetworkInformation,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<int> getDailyDataUsage() => (super.noSuchMethod(
        Invocation.method(
          #getDailyDataUsage,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> getWeeklyDataUsage() => (super.noSuchMethod(
        Invocation.method(
          #getWeeklyDataUsage,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> getMonthlyDataUsage() => (super.noSuchMethod(
        Invocation.method(
          #getMonthlyDataUsage,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<bool> checkUsageStatsPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkUsageStatsPermission,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> requestUsageStatsPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestUsageStatsPermission,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> openWifiSettings() => (super.noSuchMethod(
        Invocation.method(
          #openWifiSettings,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> startAmbientMode() => (super.noSuchMethod(
        Invocation.method(
          #startAmbientMode,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void addAppsChangedListener(void Function(Map<String, dynamic>)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addAppsChangedListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addNetworkChangedListener(
          void Function(Map<String, dynamic>)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addNetworkChangedListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WallpaperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWallpaperService extends _i1.Mock implements _i14.WallpaperService {
  MockWallpaperService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FLauncherGradient get gradient => (super.noSuchMethod(
        Invocation.getter(#gradient),
        returnValue: _FakeFLauncherGradient_0(
          this,
          Invocation.getter(#gradient),
        ),
      ) as _i2.FLauncherGradient);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> pickWallpaper() => (super.noSuchMethod(
        Invocation.method(
          #pickWallpaper,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> pickWallpaperDay() => (super.noSuchMethod(
        Invocation.method(
          #pickWallpaperDay,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> pickWallpaperNight() => (super.noSuchMethod(
        Invocation.method(
          #pickWallpaperNight,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setGradient(_i2.FLauncherGradient? fLauncherGradient) =>
      (super.noSuchMethod(
        Invocation.method(
          #setGradient,
          [fLauncherGradient],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppsService extends _i1.Mock implements _i15.AppsService {
  MockAppsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  List<_i16.App> get applications => (super.noSuchMethod(
        Invocation.getter(#applications),
        returnValue: <_i16.App>[],
      ) as List<_i16.App>);

  @override
  List<_i3.LauncherSection> get launcherSections => (super.noSuchMethod(
        Invocation.getter(#launcherSections),
        returnValue: <_i3.LauncherSection>[],
      ) as List<_i3.LauncherSection>);

  @override
  List<_i3.Category> get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: <_i3.Category>[],
      ) as List<_i3.Category>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void clearPendingReorderFocusPackage() => super.noSuchMethod(
        Invocation.method(
          #clearPendingReorderFocusPackage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPendingReorderFocus(
    String? packageName,
    int? categoryId,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setPendingReorderFocus,
          [
            packageName,
            categoryId,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sortCategory(_i3.Category? category) => super.noSuchMethod(
        Invocation.method(
          #sortCategory,
          [category],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i13.Uint8List> getAppBanner(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppBanner,
          [packageName],
        ),
        returnValue: _i9.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
      ) as _i9.Future<_i13.Uint8List>);

  @override
  _i9.Future<void> setCustomAppBanner(
    String? packageName,
    String? imagePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCustomAppBanner,
          [
            packageName,
            imagePath,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> removeCustomAppBanner(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCustomAppBanner,
          [packageName],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> hasCustomBanner(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #hasCustomBanner,
          [packageName],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i13.Uint8List> getAppIcon(String? packageName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppIcon,
          [packageName],
        ),
        returnValue: _i9.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
      ) as _i9.Future<_i13.Uint8List>);

  @override
  _i9.Future<void> launchApp(_i16.App? app) => (super.noSuchMethod(
        Invocation.method(
          #launchApp,
          [app],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> openAppInfo(_i16.App? app) => (super.noSuchMethod(
        Invocation.method(
          #openAppInfo,
          [app],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> uninstallApp(_i16.App? app) => (super.noSuchMethod(
        Invocation.method(
          #uninstallApp,
          [app],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> openSettings() => (super.noSuchMethod(
        Invocation.method(
          #openSettings,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool> isDefaultLauncher() => (super.noSuchMethod(
        Invocation.method(
          #isDefaultLauncher,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> startAmbientMode() => (super.noSuchMethod(
        Invocation.method(
          #startAmbientMode,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> addToCategory(
    _i16.App? app,
    _i3.Category? category, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToCategory,
          [
            app,
            category,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> addAllToCategory(
    Iterable<_i16.App>? apps,
    _i3.Category? category, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAllToCategory,
          [
            apps,
            category,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> removeFromCategory(
    _i16.App? application,
    _i3.Category? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromCategory,
          [
            application,
            category,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> autoPopulateCategory(_i3.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoPopulateCategory,
          [category],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.Category> getOrCreateFavoritesCategory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateFavoritesCategory,
          [],
        ),
        returnValue: _i9.Future<_i3.Category>.value(_FakeCategory_1(
          this,
          Invocation.method(
            #getOrCreateFavoritesCategory,
            [],
          ),
        )),
      ) as _i9.Future<_i3.Category>);

  @override
  bool isAppInFavorites(_i16.App? app) => (super.noSuchMethod(
        Invocation.method(
          #isAppInFavorites,
          [app],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> addToFavorites(_i16.App? app) => (super.noSuchMethod(
        Invocation.method(
          #addToFavorites,
          [app],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> removeFromFavorites(_i16.App? app) => (super.noSuchMethod(
        Invocation.method(
          #removeFromFavorites,
          [app],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> toggleFavorite(_i16.App? app) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [app],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> saveApplicationOrderInCategory(_i3.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApplicationOrderInCategory,
          [category],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> moveAppToAdjacentCategory(
    _i16.App? app,
    _i3.Category? currentCategory,
    _i10.AxisDirection? direction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveAppToAdjacentCategory,
          [
            app,
            currentCategory,
            direction,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void reorderApplication(
    _i3.Category? category,
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #reorderApplication,
          [
            category,
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<int> addCategory(
    String? categoryName, {
    _i3.CategorySort? sort = _i3.CategorySort.manual,
    _i3.CategoryType? type = _i3.CategoryType.row,
    int? columnsCount = 6,
    int? rowHeight = 110,
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [categoryName],
          {
            #sort: sort,
            #type: type,
            #columnsCount: columnsCount,
            #rowHeight: rowHeight,
            #shouldNotifyListeners: shouldNotifyListeners,
          },
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> updateCategory(
    int? categoryId,
    String? name,
    _i3.CategorySort? sort,
    _i3.CategoryType? type,
    int? columnsCount,
    int? rowHeight, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            categoryId,
            name,
            sort,
            type,
            columnsCount,
            rowHeight,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> addSpacer(int? height) => (super.noSuchMethod(
        Invocation.method(
          #addSpacer,
          [height],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateSpacerHeight(
    _i3.LauncherSpacer? spacer,
    int? height,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpacerHeight,
          [
            spacer,
            height,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> renameCategory(
    _i3.Category? category,
    String? categoryName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameCategory,
          [
            category,
            categoryName,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteSection(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteSection,
          [index],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void moveSectionInMemory(
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #moveSectionInMemory,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> persistSectionsOrder() => (super.noSuchMethod(
        Invocation.method(
          #persistSectionsOrder,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> moveSection(
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveSection,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> hideApplication(_i16.App? application) =>
      (super.noSuchMethod(
        Invocation.method(
          #hideApplication,
          [application],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> showApplication(_i16.App? application) =>
      (super.noSuchMethod(
        Invocation.method(
          #showApplication,
          [application],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setCategoryType(
    _i3.Category? category,
    _i3.CategoryType? type, {
    bool? shouldNotifyListeners = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategoryType,
          [
            category,
            type,
          ],
          {#shouldNotifyListeners: shouldNotifyListeners},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setCategorySort(
    _i3.Category? category,
    _i3.CategorySort? sort,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategorySort,
          [
            category,
            sort,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setCategoryColumnsCount(
    _i3.Category? category,
    int? columnsCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategoryColumnsCount,
          [
            category,
            columnsCount,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setCategoryRowHeight(
    _i3.Category? category,
    int? rowHeight,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCategoryRowHeight,
          [
            category,
            rowHeight,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i17.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get appHighlightAnimationEnabled => (super.noSuchMethod(
        Invocation.getter(#appHighlightAnimationEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get appKeyClickEnabled => (super.noSuchMethod(
        Invocation.getter(#appKeyClickEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get autoHideAppBarEnabled => (super.noSuchMethod(
        Invocation.getter(#autoHideAppBarEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get showCategoryTitles => (super.noSuchMethod(
        Invocation.getter(#showCategoryTitles),
        returnValue: false,
      ) as bool);

  @override
  bool get showAppNamesBelowIcons => (super.noSuchMethod(
        Invocation.getter(#showAppNamesBelowIcons),
        returnValue: false,
      ) as bool);

  @override
  String get themes => (super.noSuchMethod(
        Invocation.getter(#themes),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#themes),
        ),
      ) as String);

  @override
  bool get hideHighlightOutlineOnHomescreen => (super.noSuchMethod(
        Invocation.getter(#hideHighlightOutlineOnHomescreen),
        returnValue: false,
      ) as bool);

  @override
  bool get appSelectorTransitionAnimationEnabled => (super.noSuchMethod(
        Invocation.getter(#appSelectorTransitionAnimationEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get showDateInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showDateInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  bool get showTimeInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showTimeInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  String get backButtonAction => (super.noSuchMethod(
        Invocation.getter(#backButtonAction),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#backButtonAction),
        ),
      ) as String);

  @override
  String get dateFormat => (super.noSuchMethod(
        Invocation.getter(#dateFormat),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#dateFormat),
        ),
      ) as String);

  @override
  String get timeFormat => (super.noSuchMethod(
        Invocation.getter(#timeFormat),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#timeFormat),
        ),
      ) as String);

  @override
  String get dataUsagePeriod => (super.noSuchMethod(
        Invocation.getter(#dataUsagePeriod),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#dataUsagePeriod),
        ),
      ) as String);

  @override
  bool get showDataWidgetInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showDataWidgetInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  bool get showNetworkIndicatorInStatusBar => (super.noSuchMethod(
        Invocation.getter(#showNetworkIndicatorInStatusBar),
        returnValue: false,
      ) as bool);

  @override
  String get accentColorHex => (super.noSuchMethod(
        Invocation.getter(#accentColorHex),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#accentColorHex),
        ),
      ) as String);

  @override
  String get screensaverClockStyle => (super.noSuchMethod(
        Invocation.getter(#screensaverClockStyle),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.getter(#screensaverClockStyle),
        ),
      ) as String);

  @override
  _i4.Color get accentColor => (super.noSuchMethod(
        Invocation.getter(#accentColor),
        returnValue: _FakeColor_2(
          this,
          Invocation.getter(#accentColor),
        ),
      ) as _i4.Color);

  @override
  bool get timeBasedWallpaperEnabled => (super.noSuchMethod(
        Invocation.getter(#timeBasedWallpaperEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> set(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setAppHighlightAnimationEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAppHighlightAnimationEnabled,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setAppKeyClickEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAppKeyClickEnabled,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setAutoHideAppBarEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoHideAppBarEnabled,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setGradientUuid(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setGradientUuid,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setBackButtonAction(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setBackButtonAction,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setDateTimeFormat(
    String? dateFormatString,
    String? timeFormatString,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDateTimeFormat,
          [
            dateFormatString,
            timeFormatString,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setShowCategoryTitles(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowCategoryTitles,
          [show],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setShowAppNamesBelowIcons(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowAppNamesBelowIcons,
          [show],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setThemes(String? shape) => (super.noSuchMethod(
        Invocation.method(
          #setThemes,
          [shape],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setHideHighlightOutlineOnHomescreen(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHideHighlightOutlineOnHomescreen,
          [enabled],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setAppSelectorTransitionAnimationEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAppSelectorTransitionAnimationEnabled,
          [enabled],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setShowDateInStatusBar(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowDateInStatusBar,
          [show],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setShowTimeInStatusBar(bool? show) => (super.noSuchMethod(
        Invocation.method(
          #setShowTimeInStatusBar,
          [show],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setDataUsagePeriod(String? period) => (super.noSuchMethod(
        Invocation.method(
          #setDataUsagePeriod,
          [period],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setShowDataWidgetInStatusBar(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowDataWidgetInStatusBar,
          [show],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setShowNetworkIndicatorInStatusBar(bool? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShowNetworkIndicatorInStatusBar,
          [show],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setAccentColor(String? colorHex) => (super.noSuchMethod(
        Invocation.method(
          #setAccentColor,
          [colorHex],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setScreensaverClockStyle(String? style) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScreensaverClockStyle,
          [style],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> setTimeBasedWallpaperEnabled(bool? enabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setTimeBasedWallpaperEnabled,
          [enabled],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i5.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.XFile?> pickImage({
    required _i5.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i5.CameraDevice? preferredCameraDevice = _i5.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImage,
          [],
          {
            #source: source,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #preferredCameraDevice: preferredCameraDevice,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i9.Future<_i5.XFile?>.value(),
      ) as _i9.Future<_i5.XFile?>);

  @override
  _i9.Future<List<_i5.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultiImage,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i9.Future<List<_i5.XFile>>.value(<_i5.XFile>[]),
      ) as _i9.Future<List<_i5.XFile>>);

  @override
  _i9.Future<_i5.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i9.Future<_i5.XFile?>.value(),
      ) as _i9.Future<_i5.XFile?>);

  @override
  _i9.Future<List<_i5.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultipleMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i9.Future<List<_i5.XFile>>.value(<_i5.XFile>[]),
      ) as _i9.Future<List<_i5.XFile>>);

  @override
  _i9.Future<_i5.XFile?> pickVideo({
    required _i5.ImageSource? source,
    _i5.CameraDevice? preferredCameraDevice = _i5.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideo,
          [],
          {
            #source: source,
            #preferredCameraDevice: preferredCameraDevice,
            #maxDuration: maxDuration,
          },
        ),
        returnValue: _i9.Future<_i5.XFile?>.value(),
      ) as _i9.Future<_i5.XFile?>);

  @override
  _i9.Future<_i5.LostDataResponse> retrieveLostData() => (super.noSuchMethod(
        Invocation.method(
          #retrieveLostData,
          [],
        ),
        returnValue:
            _i9.Future<_i5.LostDataResponse>.value(_FakeLostDataResponse_3(
          this,
          Invocation.method(
            #retrieveLostData,
            [],
          ),
        )),
      ) as _i9.Future<_i5.LostDataResponse>);

  @override
  bool supportsImageSource(_i5.ImageSource? source) => (super.noSuchMethod(
        Invocation.method(
          #supportsImageSource,
          [source],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [FLauncherDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFLauncherDatabase extends _i1.Mock implements _i7.FLauncherDatabase {
  MockFLauncherDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get wasCreated => (super.noSuchMethod(
        Invocation.getter(#wasCreated),
        returnValue: false,
      ) as bool);

  @override
  set wasCreated(bool? _wasCreated) => super.noSuchMethod(
        Invocation.setter(
          #wasCreated,
          _wasCreated,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i6.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_4(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i6.MigrationStrategy);

  @override
  _i7.$AppsTable get apps => (super.noSuchMethod(
        Invocation.getter(#apps),
        returnValue: _Fake$AppsTable_5(
          this,
          Invocation.getter(#apps),
        ),
      ) as _i7.$AppsTable);

  @override
  _i7.$CategoriesTable get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: _Fake$CategoriesTable_6(
          this,
          Invocation.getter(#categories),
        ),
      ) as _i7.$CategoriesTable);

  @override
  _i7.$AppsCategoriesTable get appsCategories => (super.noSuchMethod(
        Invocation.getter(#appsCategories),
        returnValue: _Fake$AppsCategoriesTable_7(
          this,
          Invocation.getter(#appsCategories),
        ),
      ) as _i7.$AppsCategoriesTable);

  @override
  _i7.$LauncherSpacersTable get launcherSpacers => (super.noSuchMethod(
        Invocation.getter(#launcherSpacers),
        returnValue: _Fake$LauncherSpacersTable_8(
          this,
          Invocation.getter(#launcherSpacers),
        ),
      ) as _i7.$LauncherSpacersTable);

  @override
  _i7.$FLauncherDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$FLauncherDatabaseManager_9(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i7.$FLauncherDatabaseManager);

  @override
  Iterable<_i6.TableInfo<_i6.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i6.TableInfo<_i6.Table, Object?>>[],
      ) as Iterable<_i6.TableInfo<_i6.Table, Object?>>);

  @override
  List<_i6.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i6.DatabaseSchemaEntity>[],
      ) as List<_i6.DatabaseSchemaEntity>);

  @override
  _i6.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_10(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i6.StreamQueryUpdateRules);

  @override
  _i6.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_11(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i6.GeneratedDatabase);

  @override
  _i6.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_12(
          this,
          Invocation.getter(#options),
        ),
      ) as _i6.DriftDatabaseOptions);

  @override
  _i6.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_13(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i6.DatabaseConnection);

  @override
  _i6.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i18.dummyValue<_i6.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i6.SqlTypes);

  @override
  _i6.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_14(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i6.QueryExecutor);

  @override
  _i8.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_15(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i8.StreamQueryStore);

  @override
  _i6.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_16(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i6.DatabaseConnectionUser);

  @override
  _i9.Future<void> persistApps(Iterable<_i7.AppsCompanion>? applications) =>
      (super.noSuchMethod(
        Invocation.method(
          #persistApps,
          [applications],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateApp(
    String? packageName,
    _i7.AppsCompanion? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateApp,
          [
            packageName,
            value,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteApps(List<String>? packageNames) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteApps,
          [packageNames],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<int> insertCategory(_i6.Insertable<_i3.Category>? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCategory,
          [category],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> deleteCategory(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateCategories(List<_i7.CategoriesCompanion>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategories,
          [values],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateCategory(
    int? id,
    _i7.CategoriesCompanion? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            id,
            value,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteAppCategory(
    int? categoryId,
    String? packageName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAppCategory,
          [
            categoryId,
            packageName,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> insertAppsCategories(
          List<_i7.AppsCategoriesCompanion>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAppsCategories,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> replaceAppsCategories(
          List<_i7.AppsCategoriesCompanion>? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAppsCategories,
          [value],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<int> insertSpacer(_i6.Insertable<_i3.LauncherSpacer>? spacer) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSpacer,
          [spacer],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> deleteSpacer(int? spacerId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSpacer,
          [spacerId],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> updateSpacer(
    int? spacerId,
    _i6.Insertable<_i3.LauncherSpacer>? insertable,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpacer,
          [
            spacerId,
            insertable,
          ],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> updateSpacers(
          Iterable<_i7.LauncherSpacersCompanion>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSpacers,
          [values],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i9.Future<List<_i3.Category>>.value(<_i3.Category>[]),
      ) as _i9.Future<List<_i3.Category>>);

  @override
  _i9.Future<List<_i3.LauncherSpacer>> getLauncherSpacers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLauncherSpacers,
          [],
        ),
        returnValue:
            _i9.Future<List<_i3.LauncherSpacer>>.value(<_i3.LauncherSpacer>[]),
      ) as _i9.Future<List<_i3.LauncherSpacer>>);

  @override
  _i9.Future<List<_i7.AppCategory>> getAppsCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAppsCategories,
          [],
        ),
        returnValue:
            _i9.Future<List<_i7.AppCategory>>.value(<_i7.AppCategory>[]),
      ) as _i9.Future<List<_i7.AppCategory>>);

  @override
  _i9.Future<List<_i16.App>> getApplications() => (super.noSuchMethod(
        Invocation.method(
          #getApplications,
          [],
        ),
        returnValue: _i9.Future<List<_i16.App>>.value(<_i16.App>[]),
      ) as _i9.Future<List<_i16.App>>);

  @override
  _i9.Future<int?> nextAppCategoryOrder(int? categoryId) => (super.noSuchMethod(
        Invocation.method(
          #nextAppCategoryOrder,
          [categoryId],
        ),
        returnValue: _i9.Future<int?>.value(),
      ) as _i9.Future<int?>);

  @override
  _i6.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_17(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i6.Migrator);

  @override
  _i9.Future<void> beforeOpen(
    _i6.QueryExecutor? executor,
    _i6.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<List<Map<String, Object?>>> createStream(
          _i8.QueryStreamFetcher? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i9.Stream<List<Map<String, Object?>>>.empty(),
      ) as _i9.Stream<List<Map<String, Object?>>>);

  @override
  T alias<T, D>(
    _i6.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i18.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i6.TableInfo<_i6.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i6.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Stream<Set<_i6.TableUpdate>> tableUpdates(
          [_i6.TableUpdateQuery? query = const _i6.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i9.Stream<Set<_i6.TableUpdate>>.empty(),
      ) as _i9.Stream<Set<_i6.TableUpdate>>);

  @override
  _i9.Future<T> doWhenOpened<T>(
          _i9.FutureOr<T> Function(_i6.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i18.ifNotNull(
              _i18.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i9.Future<T>.value(v),
            ) ??
            _FakeFuture_18<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i9.Future<T>);

  @override
  _i6.InsertStatement<T, D> into<T extends _i6.Table, D>(
          _i6.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_19<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i6.InsertStatement<T, D>);

  @override
  _i6.UpdateStatement<Tbl, R> update<Tbl extends _i6.Table, R>(
          _i6.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_20<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i6.UpdateStatement<Tbl, R>);

  @override
  _i6.SimpleSelectStatement<T, R> select<T extends _i6.HasResultSet, R>(
    _i6.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_21<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i6.SimpleSelectStatement<T, R>);

  @override
  _i6.JoinedSelectStatement<T, R> selectOnly<T extends _i6.HasResultSet, R>(
    _i6.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_22<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i6.JoinedSelectStatement<T, R>);

  @override
  _i6.Selectable<_i6.TypedResult> selectExpressions(
          Iterable<_i6.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeSelectable_23<_i6.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i6.Selectable<_i6.TypedResult>);

  @override
  _i6.DeleteStatement<T, D> delete<T extends _i6.Table, D>(
          _i6.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_24<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i6.DeleteStatement<T, D>);

  @override
  _i9.Future<int> customUpdate(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.TableInfo<_i6.Table, dynamic>>? updates,
    _i6.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> customInsert(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.TableInfo<_i6.Table, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<List<_i6.QueryRow>> customWriteReturning(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.TableInfo<_i6.Table, dynamic>>? updates,
    _i6.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i9.Future<List<_i6.QueryRow>>.value(<_i6.QueryRow>[]),
      ) as _i9.Future<List<_i6.QueryRow>>);

  @override
  _i6.Selectable<_i6.QueryRow> customSelect(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_23<_i6.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i6.Selectable<_i6.QueryRow>);

  @override
  _i6.Selectable<_i6.QueryRow> customSelectQuery(
    String? query, {
    List<_i6.Variable<Object>>? variables = const [],
    Set<_i6.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_23<_i6.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i6.Selectable<_i6.QueryRow>);

  @override
  _i9.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<T> transaction<T>(
    _i9.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i18.ifNotNull(
              _i18.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i9.Future<T>.value(v),
            ) ??
            _FakeFuture_18<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i9.Future<T>);

  @override
  _i9.Future<T> exclusively<T>(_i9.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i18.ifNotNull(
              _i18.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i9.Future<T>.value(v),
            ) ??
            _FakeFuture_18<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i9.Future<T>);

  @override
  _i9.Future<void> batch(_i9.FutureOr<void> Function(_i6.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i6.GenerationContext $write(
    _i6.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_25(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i6.GenerationContext);

  @override
  _i6.GenerationContext $writeInsertable(
    _i6.TableInfo<_i6.Table, dynamic>? table,
    _i6.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_25(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i6.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [ImageProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageProvider<T extends Object> extends _i1.Mock
    implements _i10.ImageProvider<T> {
  MockImageProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.ImageStream resolve(_i10.ImageConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolve,
          [configuration],
        ),
        returnValue: _FakeImageStream_26(
          this,
          Invocation.method(
            #resolve,
            [configuration],
          ),
        ),
      ) as _i10.ImageStream);

  @override
  _i10.ImageStream createStream(_i10.ImageConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [configuration],
        ),
        returnValue: _FakeImageStream_26(
          this,
          Invocation.method(
            #createStream,
            [configuration],
          ),
        ),
      ) as _i10.ImageStream);

  @override
  _i9.Future<_i10.ImageCacheStatus?> obtainCacheStatus({
    required _i10.ImageConfiguration? configuration,
    _i10.ImageErrorListener? handleError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #obtainCacheStatus,
          [],
          {
            #configuration: configuration,
            #handleError: handleError,
          },
        ),
        returnValue: _i9.Future<_i10.ImageCacheStatus?>.value(),
      ) as _i9.Future<_i10.ImageCacheStatus?>);

  @override
  void resolveStreamForKey(
    _i10.ImageConfiguration? configuration,
    _i10.ImageStream? stream,
    T? key,
    _i10.ImageErrorListener? handleError,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #resolveStreamForKey,
          [
            configuration,
            stream,
            key,
            handleError,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<bool> evict({
    _i10.ImageCache? cache,
    _i10.ImageConfiguration? configuration = _i10.ImageConfiguration.empty,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #evict,
          [],
          {
            #cache: cache,
            #configuration: configuration,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<T> obtainKey(_i10.ImageConfiguration? configuration) =>
      (super.noSuchMethod(
        Invocation.method(
          #obtainKey,
          [configuration],
        ),
        returnValue: _i18.ifNotNull(
              _i18.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #obtainKey,
                  [configuration],
                ),
              ),
              (T v) => _i9.Future<T>.value(v),
            ) ??
            _FakeFuture_18<T>(
              this,
              Invocation.method(
                #obtainKey,
                [configuration],
              ),
            ),
      ) as _i9.Future<T>);

  @override
  _i10.ImageStreamCompleter loadBuffer(
    T? key,
    _i10.DecoderBufferCallback? decode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadBuffer,
          [
            key,
            decode,
          ],
        ),
        returnValue: _FakeImageStreamCompleter_27(
          this,
          Invocation.method(
            #loadBuffer,
            [
              key,
              decode,
            ],
          ),
        ),
      ) as _i10.ImageStreamCompleter);

  @override
  _i10.ImageStreamCompleter loadImage(
    T? key,
    _i10.ImageDecoderCallback? decode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadImage,
          [
            key,
            decode,
          ],
        ),
        returnValue: _FakeImageStreamCompleter_27(
          this,
          Invocation.method(
            #loadImage,
            [
              key,
              decode,
            ],
          ),
        ),
      ) as _i10.ImageStreamCompleter);
}
